// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: marker_types.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMarkerType = `-- name: CreateMarkerType :one
INSERT INTO marker_types (tournament_id, name, color, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, tournament_id, name, color, sort_order, created_at
`

type CreateMarkerTypeParams struct {
	TournamentID pgtype.UUID
	Name         string
	Color        string
	SortOrder    int32
}

func (q *Queries) CreateMarkerType(ctx context.Context, arg CreateMarkerTypeParams) (MarkerType, error) {
	row := q.db.QueryRow(ctx, createMarkerType,
		arg.TournamentID,
		arg.Name,
		arg.Color,
		arg.SortOrder,
	)
	var i MarkerType
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMarkerType = `-- name: DeleteMarkerType :execrows
DELETE FROM marker_types WHERE id = $1
`

func (q *Queries) DeleteMarkerType(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMarkerType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMarkerType = `-- name: GetMarkerType :one
SELECT id, tournament_id, name, color, sort_order, created_at FROM marker_types WHERE id = $1
`

func (q *Queries) GetMarkerType(ctx context.Context, id pgtype.UUID) (MarkerType, error) {
	row := q.db.QueryRow(ctx, getMarkerType, id)
	var i MarkerType
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listMarkerTypesByTournament = `-- name: ListMarkerTypesByTournament :many
SELECT id, tournament_id, name, color, sort_order, created_at
FROM marker_types
WHERE tournament_id = $1
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListMarkerTypesByTournament(ctx context.Context, tournamentID pgtype.UUID) ([]MarkerType, error) {
	rows, err := q.db.Query(ctx, listMarkerTypesByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkerType
	for rows.Next() {
		var i MarkerType
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Name,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarkerType = `-- name: UpdateMarkerType :one
UPDATE marker_types
SET
  name       = COALESCE($1, name),
  color      = COALESCE($2, color),
  sort_order = COALESCE($3, sort_order)
WHERE id = $4
RETURNING id, tournament_id, name, color, sort_order, created_at
`

type UpdateMarkerTypeParams struct {
	Name      *string
	Color     *string
	SortOrder *int32
	ID        pgtype.UUID
}

func (q *Queries) UpdateMarkerType(ctx context.Context, arg UpdateMarkerTypeParams) (MarkerType, error) {
	row := q.db.QueryRow(ctx, updateMarkerType,
		arg.Name,
		arg.Color,
		arg.SortOrder,
		arg.ID,
	)
	var i MarkerType
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
