// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMarkersByTeamAndType = `-- name: CountMarkersByTeamAndType :many
SELECT
  m.marker_type_id,
  mt.name  AS marker_type_name,
  mt.color AS marker_type_color,
  COUNT(*) AS count
FROM markers m
JOIN runs r ON r.id = m.run_id
LEFT JOIN marker_types mt ON mt.id = m.marker_type_id
WHERE r.team_id = $1
GROUP BY m.marker_type_id, mt.name, mt.color
`

type CountMarkersByTeamAndTypeRow struct {
	MarkerTypeID    pgtype.UUID
	MarkerTypeName  *string
	MarkerTypeColor *string
	Count           int64
}

func (q *Queries) CountMarkersByTeamAndType(ctx context.Context, teamID pgtype.UUID) ([]CountMarkersByTeamAndTypeRow, error) {
	rows, err := q.db.Query(ctx, countMarkersByTeamAndType, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMarkersByTeamAndTypeRow
	for rows.Next() {
		var i CountMarkersByTeamAndTypeRow
		if err := rows.Scan(
			&i.MarkerTypeID,
			&i.MarkerTypeName,
			&i.MarkerTypeColor,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMarker = `-- name: CreateMarker :one
INSERT INTO markers (run_id, author_id, run_offset_sec, label, marker_type_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, author_id, run_offset_sec, label, created_at, marker_type_id
`

type CreateMarkerParams struct {
	RunID        pgtype.UUID
	AuthorID     pgtype.UUID
	RunOffsetSec float64
	Label        string
	MarkerTypeID pgtype.UUID
}

func (q *Queries) CreateMarker(ctx context.Context, arg CreateMarkerParams) (Marker, error) {
	row := q.db.QueryRow(ctx, createMarker,
		arg.RunID,
		arg.AuthorID,
		arg.RunOffsetSec,
		arg.Label,
		arg.MarkerTypeID,
	)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AuthorID,
		&i.RunOffsetSec,
		&i.Label,
		&i.CreatedAt,
		&i.MarkerTypeID,
	)
	return i, err
}

const deleteMarker = `-- name: DeleteMarker :execrows
DELETE FROM markers WHERE id = $1
`

func (q *Queries) DeleteMarker(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMarker, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMarker = `-- name: GetMarker :one
SELECT
  m.id, m.run_id, m.author_id, m.run_offset_sec, m.label, m.created_at, m.marker_type_id,
  mt.name  AS marker_type_name,
  mt.color AS marker_type_color
FROM markers m
LEFT JOIN marker_types mt ON mt.id = m.marker_type_id
WHERE m.id = $1
`

type GetMarkerRow struct {
	ID              pgtype.UUID
	RunID           pgtype.UUID
	AuthorID        pgtype.UUID
	RunOffsetSec    float64
	Label           string
	CreatedAt       pgtype.Timestamptz
	MarkerTypeID    pgtype.UUID
	MarkerTypeName  *string
	MarkerTypeColor *string
}

func (q *Queries) GetMarker(ctx context.Context, id pgtype.UUID) (GetMarkerRow, error) {
	row := q.db.QueryRow(ctx, getMarker, id)
	var i GetMarkerRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AuthorID,
		&i.RunOffsetSec,
		&i.Label,
		&i.CreatedAt,
		&i.MarkerTypeID,
		&i.MarkerTypeName,
		&i.MarkerTypeColor,
	)
	return i, err
}

const listMarkersByRun = `-- name: ListMarkersByRun :many
SELECT
  m.id, m.run_id, m.author_id, m.run_offset_sec, m.label, m.created_at, m.marker_type_id,
  mt.name  AS marker_type_name,
  mt.color AS marker_type_color
FROM markers m
LEFT JOIN marker_types mt ON mt.id = m.marker_type_id
WHERE m.run_id = $2
  AND ($3::double precision IS NULL
       OR (m.run_offset_sec, m.id) > ($3::double precision, $4::uuid))
  AND (COALESCE(array_length($5::uuid[], 1), 0) = 0
       OR m.marker_type_id = ANY($5::uuid[]))
ORDER BY m.run_offset_sec ASC, m.id ASC
LIMIT $1
`

type ListMarkersByRunParams struct {
	Limit           int32
	RunID           pgtype.UUID
	CursorRunOffset *float64
	CursorID        pgtype.UUID
	MarkerTypeIds   []pgtype.UUID
}

type ListMarkersByRunRow struct {
	ID              pgtype.UUID
	RunID           pgtype.UUID
	AuthorID        pgtype.UUID
	RunOffsetSec    float64
	Label           string
	CreatedAt       pgtype.Timestamptz
	MarkerTypeID    pgtype.UUID
	MarkerTypeName  *string
	MarkerTypeColor *string
}

func (q *Queries) ListMarkersByRun(ctx context.Context, arg ListMarkersByRunParams) ([]ListMarkersByRunRow, error) {
	rows, err := q.db.Query(ctx, listMarkersByRun,
		arg.Limit,
		arg.RunID,
		arg.CursorRunOffset,
		arg.CursorID,
		arg.MarkerTypeIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarkersByRunRow
	for rows.Next() {
		var i ListMarkersByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AuthorID,
			&i.RunOffsetSec,
			&i.Label,
			&i.CreatedAt,
			&i.MarkerTypeID,
			&i.MarkerTypeName,
			&i.MarkerTypeColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarker = `-- name: UpdateMarker :one
UPDATE markers
SET
  run_offset_sec = COALESCE($1, run_offset_sec),
  label          = COALESCE($2, label),
  marker_type_id = CASE WHEN $3::bool
                        THEN $4::uuid
                        ELSE marker_type_id END
WHERE id = $5
RETURNING id, run_id, author_id, run_offset_sec, label, created_at, marker_type_id
`

type UpdateMarkerParams struct {
	RunOffsetSec  *float64
	Label         *string
	SetMarkerType bool
	MarkerTypeID  pgtype.UUID
	ID            pgtype.UUID
}

func (q *Queries) UpdateMarker(ctx context.Context, arg UpdateMarkerParams) (Marker, error) {
	row := q.db.QueryRow(ctx, updateMarker,
		arg.RunOffsetSec,
		arg.Label,
		arg.SetMarkerType,
		arg.MarkerTypeID,
		arg.ID,
	)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AuthorID,
		&i.RunOffsetSec,
		&i.Label,
		&i.CreatedAt,
		&i.MarkerTypeID,
	)
	return i, err
}
